### ISSUE TITLE
wof:belongsto property contains a mix of strings and integers

### ISSUE THREAD

**Issue by missinglink** [whosonfirst/whosonfirst-properties#71]
eg: https://data.whosonfirst.org/420/784/501/420784501.geojson

**Comment by stepps00** [comment]
This should actually be fixed in the GitHub records, see: https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/master/data/420/784/501/420784501.geojson

[This PR](https://github.com/whosonfirst-data/whosonfirst-data/pull/1190) standardized many properties, including the `wof:belongsto` property to remove strings. Suggest leaving open until we reconcile GitHub/whosonfirst.org.

**Comment by missinglink** [comment]
oh damn, I assumed the `data.whosonfirst.org` data was verbatim the same data as on github, apparently this is not true!

what's the lag between the two?

**Comment by missinglink** [comment]
also that PR is awesome, fixes a lot of those type issues across the board!

**Comment by nvkelso** [comment]
> oh damn, I assumed the data.whosonfirst.org data was verbatim the same data as on github, apparently this is not true!

This has been true in the past, but they started to diverge a few weeks ago when we started to merge to master again – there were too many PRs that needed to be finished / 2x blocking each other. We're still working thru some workflow kinks to get all the distributions working again (including SQLite and the Spelunker).

**Comment by nvkelso** [comment]
Closed via https://github.com/whosonfirst-data/whosonfirst-data/pull/1190.

**Comment by thisisaaronland** [comment]
@missinglink As far as the "update all the things from master" work goes there are a series of overlapping issues/blockers, that include:

* This is no longer the exclusive focus of my daylight hours; I am able to devote some amount of time to it in the course of other things but there are other things now.
* The `go-whosonfirst-dist` code is being / has been refactored to first create a SQLite database from a fresh clone (rather than the hilarity-inducing nightmare of pulling from master) and use that database to produce all the other things. Meta files, bundles, shapefiles eventually and so on.
* The code to generate bundles needs to be refactored to use `go-whosonfirst-index` so it can build bundles using the SQLite database.
* All of that needs to be packaged up  so that it can run on demand, as in be triggered by one or more pushes to master and rebuilt once an hour, or once a day or whatever and also push both distributions and individual files up to S3, the Spelunker, etc. ideally without having to clone or copy the entire dataset.

It's all being worked on (slowly) but if you just need a fresh SQLite database it can be built manually for now like this:

```
wof-dist-build {REPO_NAME}
```

For a complete list of options, pass it the `-h` flag.
